/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("meters").insert([
    {
      id: 1,
      model: "Gyr E330",
      maximumCurrent: 120,
      ratedCurrent: 23,
      ratedVoltage: 361,
      activeConstantValue: 4793,
      reactiveConstantValue: 768.9,
      brand_id: 3,
      connection_id: 2,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 2,
    },
    {
      id: 2,
      model: "T8S1",
      maximumCurrent: 47,
      ratedCurrent: 27,
      ratedVoltage: 139,
      activeConstantValue: 94.74,
      reactiveConstantValue: 8.89,
      brand_id: 5,
      connection_id: 2,
      activeConstantUnit_id: 2,
      reactiveConstantUnit_id: 2,
    },
    {
      id: 3,
      model: "A-1052",
      maximumCurrent: 67,
      ratedCurrent: 26,
      ratedVoltage: 10,
      activeConstantValue: 0.7783,
      reactiveConstantValue: 6384,
      brand_id: 4,
      connection_id: 2,
      activeConstantUnit_id: 2,
      reactiveConstantUnit_id: 1,
    },
    {
      id: 4,
      model: "Alpha-2",
      maximumCurrent: 48,
      ratedCurrent: 20,
      ratedVoltage: 329,
      activeConstantValue: 19405,
      reactiveConstantValue: 52814,
      brand_id: 5,
      connection_id: 2,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 1,
    },
    {
      id: 5,
      model: "ACE-3000",
      maximumCurrent: 62,
      ratedCurrent: 40,
      ratedVoltage: 256,
      activeConstantValue: 54644,
      reactiveConstantValue: 176633,
      brand_id: 5,
      connection_id: 1,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 1,
    },
    {
      id: 6,
      model: "HXE-310",
      maximumCurrent: 78,
      ratedCurrent: 20,
      ratedVoltage: 313,
      activeConstantValue: 5514,
      reactiveConstantValue: 268.2,
      brand_id: 3,
      connection_id: 2,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 2,
    },
    {
      id: 7,
      model: "Gyr ZMG405",
      maximumCurrent: 61,
      ratedCurrent: 1,
      ratedVoltage: 299,
      activeConstantValue: 395,
      reactiveConstantValue: 1.293,
      brand_id: 2,
      connection_id: 1,
      activeConstantUnit_id: 2,
      reactiveConstantUnit_id: 2,
    },
    {
      id: 8,
      model: "A-150",
      maximumCurrent: 41,
      ratedCurrent: 1,
      ratedVoltage: 192,
      activeConstantValue: 3022,
      reactiveConstantValue: 3353,
      brand_id: 3,
      connection_id: 2,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 1,
    },
    {
      id: 9,
      model: "ACE-1000",
      maximumCurrent: 93,
      ratedCurrent: 30,
      ratedVoltage: 207,
      activeConstantValue: 391,
      reactiveConstantValue: 9701,
      brand_id: 5,
      connection_id: 2,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 1,
    },
    {
      id: 10,
      model: "Gyr SP2301",
      maximumCurrent: 9,
      ratedCurrent: 40,
      ratedVoltage: 16,
      activeConstantValue: 539,
      reactiveConstantValue: 0.4674,
      brand_id: 3,
      connection_id: 1,
      activeConstantUnit_id: 1,
      reactiveConstantUnit_id: 2,
    },
    {
      id: 11,
      model: "M5A1",
      maximumCurrent: 50,
      ratedCurrent: 15,
      ratedVoltage: 2,
      activeConstantValue: 13.98,
      reactiveConstantValue: 69,
      brand_id: 2,
      connection_id: 2,
      activeConstantUnit_id: 2,
      reactiveConstantUnit_id: 1,
    },
  ]);
};
