/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  // await knex('history').insert([
  // { id: 1, saved: '08/08/2022 11:40', essay: 'Ensayo de contraste 1%', items_raw: '[{"essayTemplateStep":{"id":1,"order":1,"actions_raw_data":{"actions":[{"actionName":"Identificación de usuario","userId":null},{"actionName":"Identificación de puestos","hasManufacturingInformation":false,"stands":[{"standIndex":1,"isActive":true,"meterId":12,"serialNumber":null,"yearOfProduction":null},{"standIndex":2,"isActive":false,"meterId":null,"serialNumber":null,"yearOfProduction":null},{"standIndex":3,"isActive":false,"meterId":null,"serialNumber":null,"yearOfProduction":null}]}]},"essay_template_id":1,"step_id":7,"foreign":{"step":{"id":7,"name":"Preparación"}}},"reportData":{}},{"essayTemplateStep":{"id":2,"order":2,"actions_raw_data":{"actions":[{"actionName":"Valores para ajuste de fotocélula","phaseL1":{"voltageU1":2200,"currentI1":40,"anglePhi1":0},"phaseL2":{"voltageU2":2200,"currentI2":40,"anglePhi2":0},"phaseL3":{"voltageU3":2200,"currentI3":40,"anglePhi3":0}},{"actionName":"Realizar ajuste de fotocélula","photocellAdjustmentExecutionComplete":null}]},"essay_template_id":1,"step_id":6,"foreign":{"step":{"id":6,"name":"Ajuste de fotocélulas"}}},"reportData":{}},{"essayTemplateStep":{"id":3,"order":3,"actions_raw_data":{"actions":[{"actionName":"Valores generales de la prueba","meterConstant":0,"phaseL1":{"voltageU1":2200,"currentI1":50,"anglePhi1":0},"phaseL2":{"voltageU2":2200,"currentI2":50,"anglePhi2":0},"phaseL3":{"voltageU3":2200,"currentI3":50,"anglePhi3":0}},{"actionName":"Parámetros para la prueba de contraste","maxAllowedError":1,"meterPulses":5,"numberOfDiscardedResults":0},{"actionName":"Realizar prueba de contraste","executionComplete":null}]},"essay_template_id":1,"step_id":4,"foreign":{"step":{"id":4,"name":"Prueba de constraste"}}},"reportData":{"reportName":"ENSAYO DE CONTRASTE","executionDateString":"08/08/2022 11:39","maxAllowedError":1,"userName":"Banda, Juan - OPERACIONES","standsLength":1,"stands":[{"standIndex":1,"brandModel":"Landis - ACE-3000","errorValue":-1.32,"result":"DISAPPROVED"}],"executionSeconds":8}},{"essayTemplateStep":{"id":4,"order":4,"actions_raw_data":[],"essay_template_id":1,"step_id":1,"foreign":{"step":{"id":1,"name":"Reporte"}}},"reportData":{}}]' },
  // ]);
};
