/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("history_essay").insert([
    {
      id: 1,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "111",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 2,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "222",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 3,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "333",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 4,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "444",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 5,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "555",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 6,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "666",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 7,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "777",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 8,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "888",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 9,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "999",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 10,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Arranque",
      meter_id: 7,
      serial_number: "000",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 11,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "111",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 12,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "222",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 13,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "333",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 14,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "444",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 15,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "555",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 16,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "666",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 17,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "777",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 18,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "888",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 19,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "999",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 20,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Contraste",
      meter_id: 7,
      serial_number: "000",
      year_of_production: "2024",
      result_status_enum: "Failed",
    },
    {
      id: 21,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "111",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 22,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "222",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 23,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "333",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 24,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "444",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 25,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "555",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 26,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "666",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 27,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "777",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 28,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "888",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 29,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "999",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
    {
      id: 30,
      saved_time: 1713565304894,
      essay_name: "Completo",
      step_name: "Vacío",
      meter_id: 7,
      serial_number: "000",
      year_of_production: "2024",
      result_status_enum: "Approved",
    },
  ]);
};
