/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // await knex("history_essay_step_stand").insert([
  //   {
  //     id: 1,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Arranque",
  //     meter_id: 11,
  //     serial_number: 111,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 0,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 2,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Arranque",
  //     meter_id: 11,
  //     serial_number: 222,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 1,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 3,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Arranque",
  //     meter_id: 10,
  //     serial_number: 333,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 0,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 4,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Arranque",
  //     meter_id: 10,
  //     serial_number: 777,
  //     year_of_production: 2003,
  //     result_status_enum: "Failed",
  //     result_value: 1,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 5,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Contraste",
  //     meter_id: 11,
  //     serial_number: 111,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: -5.6,
  //     result_unit: '%',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 6,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Contraste",
  //     meter_id: 11,
  //     serial_number: 222,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 8.78,
  //     result_unit: '%',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 7,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Contraste",
  //     meter_id: 10,
  //     serial_number: 333,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 22.5,
  //     result_unit: '%',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 8,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Contraste",
  //     meter_id: 10,
  //     serial_number: 777,
  //     year_of_production: 2003,
  //     result_status_enum: "Failed",
  //     result_value: 13.15,
  //     result_unit: '%',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 9,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Vacío",
  //     meter_id: 11,
  //     serial_number: 111,
  //     year_of_production: 2024,
  //     result_status_enum: "Approved",
  //     result_value: 1,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 10,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Vacío",
  //     meter_id: 11,
  //     serial_number: 222,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 4,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 11,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Vacío",
  //     meter_id: 10,
  //     serial_number: 333,
  //     year_of_production: 2024,
  //     result_status_enum: "Failed",
  //     result_value: 2,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  //   {
  //     id: 12,
  //     saved_time: 1715007302021,
  //     essay_name: "Completo",
  //     step_name: "Vacío",
  //     meter_id: 10,
  //     serial_number: 777,
  //     year_of_production: 2003,
  //     result_status_enum: "Failed",
  //     result_value: 2,
  //     result_unit: 'Impulsos',
  //     history_essay_id: 1,
  //   },
  // ]);
};
