export enum PageUrlName {
  root = '/',
  availableTest = 'ensayos-disponibles',
  historyAndReports = 'historial-y-reportes',
  meters = 'medidores',
  brands = 'marcas',
  users = 'usuarios',
  import = 'importar',
  export = 'exportar',
  newEssayTemplate = 'nuevo-template-ensayo',
  editEssayTemplate = 'editar-template-ensayo',
  executeEssay = 'ejecutar-ensayo',
  seeReport = 'ver-reporte',
  dashboard = 'estadisticas',
  terminal = 'terminal',
}
